import "./globals.css";
import { Montserrat, Inter, Frank_Ruhl_Libre } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'] });
const frankRuhlLibre = Frank_Ruhl_Libre({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${montserrat.className} ${inter.className} ${frankRuhlLibre.className}`}>
        {children}
      </body>
    </html>
  );
}
