import "./globals.css";
import { Montserrat, Inter, Frank_Ruhl_Libre } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' });
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const frankRuhlLibre = Frank_Ruhl_Libre({ subsets: ['latin'], variable: '--font-frank-ruhl-libre' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${inter.className} ${frankRuhlLibre.className}`}>
        {children}
      </body>
    </html>
  );
}
